### ISSUE TITLE
Add admincraft-websocket image for amd64 (error: websocket exited with code 1)

### ISSUE THREAD

**Issue by remklov** [joanroig/admincraft#49]
I am trying to get the websocket running, but i get this error in the docker logs:
> websocket exited with code 1

On inspecting the logs of the websocket container i see 
> exec /usr/local/bin/docker-entrypoint.sh: exec format error

In my google research this can be caused by running a binary for architecture X on a machine with architecture Y, but i cant get what architecture is the problem here.

The Server is running on a Ubuntu 24.04 VM in Proxmox on a BeelinkMini with amd64 architecture. The websocket image seems to require linux/arm64.

Anyone can help solving this?

**Comment by joanroig** [comment]
Hello @remklov, you are right. The docker image I provide is compiled on arm64, I will have a look on how to provide binaries for amd64 and let you know.

**Comment by joanroig** [comment]
@remklov please try again, I have added an image for arm64: https://hub.docker.com/r/joanroig/admincraft-websocket/tags
